### ISSUE TITLE
doubt about installation

### ISSUE THREAD

**Issue by emilioTejada** [jssotomdz/winamp-snap#1]
Hello. Thank you very much for the idea of a winamp in ubuntu :)

If I install as you indicate, with a "snap install winamp" I get:

error: The "winamp" snap is not available in stable but is available to install on the following channels:

        beta snap install --beta winamp
        edge snap install --edge winamp

I install the "edge"?

Thanks

**Comment by jssotomdz** [comment]
Hi, sorry for the very late reply. Yes, feel free to install any channel you want. Ideally, stable is the channel that has been tested and is known to work. With Winamp though, since it's a Windows app running over Wine and there will be some issues, I published it over both beta and edge channels. Edge will always have the latest build while beta has the latest that I tested and made sure that at least there are no regressions. so feel free to try any channel!
